### ISSUE TITLE
Bower repository contains different files

### ISSUE THREAD

**Issue by enscope** [wilsonpage/sass-import-once#18]
It seems, that 0.1.1 bower package contains invalid SCSS source file. Please check the package, I would love to install it using composer instead of static including in project.

**Comment by wilsonpage** [comment]
Do you have a link?

**Comment by enscope** [comment]
I don't, but try to do a Bower install for example and you will get incorrect package.

    mx-mbpro:bower mx$ bower install sass-import-once
    bower sass-import-once#*        cached git://github.com/wilsonpage/sass-import-once.git#0.1.1
    bower sass-import-once#*      validate 0.1.1 against git://github.com/wilsonpage/sass-import-once.git#*
    bower sass-import-once#~0.1.1  install sass-import-once#0.1.1
    sass-import-once#0.1.1 bower_components/sass-import-once
    mx-mbpro:bower mx$ cat bower_components/sass-import-once/_sass-import-once.scss 
    $modules: () !default;
    @mixin exports($name) {
      @if (index($modules, $name) == false) {
        $modules: append($modules, $name);
        @content;
      }
    }

**Comment by wilsonpage** [comment]
This was because a new version hadn't been stamped. Stamped `v0.2.0` and now fixed.
